@startuml
entity Scheduler as s
participant Github_Action as action
database Github_API as gh

s -> action: Check for Inactive Contributors
activate action
action -> gh: request auth
action <-- gh: session token
action -> gh: Get org members
action <--  gh:(List of members)
action -> gh: has committed since {absence}?

note right
"absence" is the duration of inactivity
end note

group absence is > activity days?
    action -> gh: move to Alumni
    group has custom permission?
    action -> gh: remove custom permissions
    end
    deactivate
    end


group
@enduml