@startuml
entity Scheduler as s
participant Github_Action as action
database Github_Org as gh

s -> action: Check for Inactive Contributors
action -> gh: GetListOfMembers
action <--  gh:FullMemberInfo...

note right 
The Memberlist has all the attributes of each member
end note

group Last Commit is > 365 days?
    action -> gh: move to Alumni
    group has custom permission?
    action -> gh: remove custom permissions
    end
    end

group
@enduml
