name: Integration

on:
  workflow_run:
    workflows: ["Read-Only"]
    branches: [ main ]
    types:
      - completed

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
    - name: Run the action itself, on the https://github.com/test-inactive-contributor-action org
      uses: ./
      with:
        github-orgname: test-inactive-contributor-action
        maximum-absence-before-retirement: 1 second
        alumni-team: test-Alumni
        read-only: false
      env:
        GITHUB_TOKEN: ${{ secrets.OCTOKIT_TOKEN }} 