name: Read-Only
on:
  workflow_run:
    workflows: ["Test"]
    branches: [ main ]
    types:
      - completed

jobs:
  read-only:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run the action itself, on the https://github.com/test-inactive-contributor-action org
      uses: ./
      with:
        github-orgname: test-inactive-contributor-action
        maximum-absence-before-retirement: 1 second
        alumni-team: test-Alumni
        read-only: true
      env:
        GITHUB_TOKEN: ${{ secrets.OCTOKIT_TOKEN }} 
  