name: Release

on:
  push:
    branches: [release/*]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: cucumber/action-create-github-release@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
