name: Build & test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches:
      - main

jobs:
  integration-dry-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run the action itself, on the https://github.com/test-inactive-contributor-action org
      uses: ./
      with:
        github-orgname: test-inactive-contributor-action
        maximum-absence-before-retirement: 1 second
        alumni-team: test-Alumni
        dry-run: true
      env:
        GITHUB_TOKEN: ${{ secrets.OCTOKIT_TOKEN }} 
  integration-tests:
    needs: integration-dry-run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run the action itself, on the https://github.com/test-inactive-contributor-action org
      uses: ./
      with:
        github-orgname: test-inactive-contributor-action
        maximum-absence-before-retirement: 1 second
        alumni-team: test-Alumni
        dry-run: false
      env:
        GITHUB_TOKEN: ${{ secrets.OCTOKIT_TOKEN }} 
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.OCTOKIT_TOKEN }}
