name: Build & test

on:
  push:
    branches: [ "*" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        github-orgname: test-inactive-contributor-action
      env:
        GITHUB_TOKEN: ${{ secrets.OCTOKIT_TOKEN }} 
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CUCUMBER_PUBLISH_TOKEN: ${{ secrets.CUCUMBER_PUBLISH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.OCTOKIT_TOKEN }}
