name: Update

on:
  schedule:
    # weekly on Sunday at 13:00 UTC
    - cron: '0 13 * * 0'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Run the action against the cucumber org
      uses: ./
      with:
        github-orgname: cucumber
        maximum-absence-before-retirement: 1 year
        alumni-team: Alumni
        read-only: true
      env:
        GITHUB_TOKEN: ${{ secrets.OCTOKIT_TOKEN }} 